controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    eyes_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    forward_head_controller:
      type: forward_command_controller/ForwardCommandController

    jaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    r_shoulder_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    r_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Set joint state broadcaster to push zero joint states to all other than movable joints
joint_state_broadcaster:
  ros__parameters:
    extra_joints:
    - head_roll_joint
    - head_tilt_joint
    - waist_pan_joint
    - waist_roll_joint
    #- r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    #- r_shoulder_out_joint
    - r_thumb1_joint
    #- r_thumb_joint
    - r_thumb3_joint
    #- r_index1_joint
    - r_index_joint
    - r_index3_joint
    #- r_middle1_joint
    - r_middle_joint
    - r_middle3_joint
    - r_ring1_joint
    #- r_ring_joint
    - r_ring3_joint
    - r_ring4_joint
    - r_pinky1_joint
    #- r_pinky_joint
    - r_pinky3_joint
    - r_pinky4_joint
    - r_wrist_roll_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_shoulder_out_joint
    - l_thumb1_joint
    - l_thumb_joint
    - l_thumb3_joint
    - l_index1_joint
    - l_index_joint
    - l_index3_joint
    - l_middle1_joint
    - l_middle_joint
    - l_middle3_joint
    - l_ring1_joint
    - l_ring_joint
    - l_ring3_joint
    - l_ring4_joint
    - l_pinky1_joint
    - l_pinky_joint
    - l_pinky3_joint
    - l_pinky4_joint
    - l_wrist_roll_joint

r_hand_controller:
  ros__parameters:
    joints:
    - r_thumb_joint
    - r_index1_joint
    - r_middle1_joint
    - r_ring_joint
    - r_pinky_joint
    write_op_modes:
    - r_thumb_joint
    - r_index_joint
    - r_middle_joint
    - r_ring_joint
    - r_pinky_joint
    allow_partial_joints_goal: true
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 20.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

head_controller:
  ros__parameters:
    joints:
    - head_pan_joint
    - head_tilt_right_joint
    - head_tilt_left_joint
    - head_tilt_vertical_joint
    write_op_modes:
    - head_pan_joint
    - head_tilt_right_joint
    - head_tilt_left_joint
    - head_tilt_vertical_joint
    allow_partial_joints_goal: true
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20

eyes_controller:
  ros__parameters:
    joints:
    - eyes_shift_vertical_joint
    - eyes_shift_horizontal_joint
    write_op_modes:
    - eyes_shift_vertical_joint
    - eyes_shift_horizontal_joint
    allow_partial_joints_goal: true
    interface_name: position
    
    command_interfaces:
      - position
    state_interfaces:
      - position
      
    state_publish_rate: 20.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

#forward_head_controller:
#  ros__parameters:
#    joints:
#    - head_pan_joint
#    - head_tilt_right_joint
#    - head_tilt_left_joint
#    - head_tilt_vertical_joint
#    interface_name: position

jaw_controller:
  ros__parameters:
    joints:
    - head_jaw_joint
    write_op_modes:
    - head_jaw_joint
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 1.0 # Defaults to 50
    action_monitor_rate: 1.0 # Defaults to 20
    

r_shoulder_controller:
  ros__parameters:
    joints:
    - r_shoulder_lift_joint
    - r_shoulder_out_joint
    write_op_modes:
    - r_shoulder_lift_joint
    - r_shoulder_out
    allow_partial_joints_goal: true
    interface_name: position

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 20.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20